<p>I that reason is that Exception is called after trigger_error(); function and you can send also some additional information to that exception = better debugging?</p>

<p>I'm not sure but I think that's it</p>

<p><strike>example:</p>

<p>class db
{
    function connect()
    {
        mysql_Connect("lolcalhost", "root", "pass:)") or trigger_error("Test"); 
    }
}
try
{
}
catch (db 
</strike></p>